name: Build & Release Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get Dependencies
        run: |
          cd mobile_app
          flutter pub get

      - name: Build Android Release APK
        run: |
          cd mobile_app
          flutter build apk --release --no-tree-shake-icons

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: royal-shetkari-release-apk
          path: mobile_app/build/app/outputs/flutter-apk/app-release.apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest-build
          name: Latest Release Build
          draft: false
          prerelease: true
          files: mobile_app/build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
